#! /bin/sh

set -e

CONF_DIR="/etc/xivo-build-tools"
CONF_FILE="${CONF_DIR}/config"

case "$1" in
	configure)
		. "$CONF_FILE"
		! id builder >/dev/null && useradd -U -m -d /home/builder -s /bin/bash builder
		[ ! -d "$PACKAGES_DIR" ] && mkdir "$PACKAGES_DIR"
		chown builder:builder "$PACKAGES_DIR"
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
