#! /bin/sh

set -e

CONF_DIR="/etc/xivo-build-tools"
CONF_FILE="${CONF_DIR}/config"

case "$1" in
	configure)
		. "$CONF_FILE"
		! id builder >/dev/null && useradd -U -m -d /home/builder -s /bin/bash builder
		[ ! -d "$PACKAGES_DIR" ] && mkdir "$PACKAGES_DIR"
		chown builder:builder "$PACKAGES_DIR"

		groups builder | grep -q sudo
		if [ $? -eq 1 ]; then
			adduser builder sudo
			echo 'builder ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/builder
			chmod 440 /etc/sudoers.d/builder
		fi
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
